

import {
  LucideProps,
  Folder, List, File, Music, Image as ImageIcon, Video, Gamepad2, Tv, Film,
  Book, Mic, Home, Building, Users, User, Heart, Settings,
  Code, Terminal, GitBranch, Database, Cloud, Radio, BarChart,
  PieChart, LineChart, TrendingUp, DollarSign, ShoppingCart, Plane,
  Car, Train, Ship, Anchor, Globe, Map, Briefcase, School, Archive, Award, Pin,
  GanttChart, Link as LinkIcon, Library, Clock, StickyNote, Calendar, Play, Calculator, Sun, Droplets, Wind, Zap, Scale, Thermometer, Repeat,
  Split, KanbanSquare, Focus, Filter, Workflow, BookOpen, Wand2, Navigation, Rss, MonitorSmartphone, Laptop, Smartphone, Tablet, Lightbulb, Shield, Gamepad as GamepadIcon,
  Contact, QrCode, BrainCircuit, Waves, Utensils, Speaker, Trophy, Dumbbell, Trash2, GitBranch as Fishbone, Bot, Layout, Palette,
  AlarmClock, Timer, Hourglass, SunMoon, CaseSensitive, BatteryCharging, Ruler, Star, Coffee,
  Bell, Bookmark, Share2, CheckSquare, FileText, PlayCircle, ListTodo, CloudSun, Twitter, Instagram, Youtube, MessageSquare, Users as UsersIcon, Github, Layers
} from 'lucide-react';
import React from 'react';
import { PharmacyLogo } from '@/components/icons/pharmacy-logo';
import { AppLogo } from '@/components/icons/app-logo';
import { LetterGrade } from './initial-content';


export const metricIcons: Record<string, React.ElementType | Record<string, React.ElementType>> = {
    rating: Star,
    priority: TrendingUp,
    letterGrade: {
        'A+': BookOpen, 'A': BookOpen, 'A-': BookOpen, 
        'B+': BookOpen, 'B': BookOpen, 'B-': BookOpen,
        'C+': BookOpen, 'C': BookOpen, 'C-': BookOpen,
        'D': BookOpen, 'F': BookOpen
    },
    fiveStarRating: Star,
    hundredPointScale: GanttChart,
    energyScore: {
      'A+++': BatteryCharging, 'A++': BatteryCharging, 'A+': BatteryCharging, 'A': BatteryCharging,
      'B': BatteryCharging, 'C': BatteryCharging, 'D': BatteryCharging, 'E': BatteryCharging, 'F': BatteryCharging, 'G': BatteryCharging
    },
    'temperature': Thermometer,
    'size': Ruler,
    'weight': Scale,
    'waves': Waves,
    'default': CaseSensitive
};


export const iconComponents = {
  folder: Folder,
  list: List,
  file: File,
  music: Music,
  image: ImageIcon,
  video: Video,
  game: Gamepad2,
  tv: Tv,
  film: Film,
  book: BookOpen,
  podcast: Mic,
  home: Home,
  work: Briefcase,
  team: Users,
  personal: User,
  favorites: Heart,
  settings: Settings,
  dev: Code,
  cli: Terminal,
  git: GitBranch,
  db: Database,
  cloud: Cloud,
  radio: Radio,
  barChart: BarChart,
  pieChart: PieChart,
  lineChart: LineChart,
  trending: TrendingUp,
  finance: DollarSign,
  ecommerce: ShoppingCart,
  travel: Plane,
  car: Car,
  train: Train,
  ship: Ship,
  anchor: Anchor,
  world: Globe,
  map: Map,
  school: School,
  archive: Archive,
  award: Award,
  pin: Pin,
  todolist: GanttChart,
  website: LinkIcon,
  library: Library,
  inventory: Archive,
  space: Building,
  shoppingCart: ShoppingCart,
  pharmacy: PharmacyLogo,
  clock: Clock,
  notes: StickyNote,
  calendar: Calendar,
  player: AppLogo,
  '3dplayer': Gamepad2,
  github: Github,
  weather: Sun,
  calculator: Calculator,
  'financial-engineering': TrendingUp,
  currencyConverter: DollarSign,
  unitConverter: Scale,
  currencyRates: TrendingUp,
  playerControls: Play,
  navigation: Navigation,
  mediaHub: Tv,
  aiImage: Wand2,
  flowchart: Workflow,
  kanban: KanbanSquare,
  swot: Focus,
  fishbone: Fishbone,
  '5s': Filter,
  qfd: Award,
  processchart: Workflow,
  pmp: BookOpen,
  rss: Rss,
  devices: MonitorSmartphone,
  item: File,
  laptop: Laptop,
  smartphone: Smartphone,
  tablet: Tablet,
  lightbulb: Lightbulb,
  shield: Shield,
  'gamepad-2': GamepadIcon,
  'profile-card': Contact,
  'profile-share': QrCode,
  mindmap: BrainCircuit,
  futbol: Trophy,
  basketbol: Dumbbell,
  tenis: Dumbbell,
  voleybol: Dumbbell,
  yuzme: Waves,
  utensils: Utensils,
  speaker: Speaker,
  'trash-folder': Trash2,
  bot: Bot,
  layout: Layout,
  palette: Palette,
  alarm: AlarmClock,
  timer: Timer,
  stopwatch: Timer,
  hourglass: Hourglass,
  globe: Globe,
  'sun-moon': SunMoon,
  pomodoro: Coffee,
  match: Trophy,
  'league-table': List,
  fixture: Calendar,
  bell: Bell,
  thermometer: Thermometer,
  trophy: Trophy,
  bookmark: Bookmark,
  user: User,
  'share-2': Share2,
  briefcase: Briefcase,
  'monitor-smartphone': MonitorSmartphone,
  'trash-2': Trash2,
  'git-branch': GitBranch,
  'check-square': CheckSquare,
  'file-text': FileText,
  'play-circle': PlayCircle,
  'list-todo': ListTodo,
  'cloud-sun': CloudSun,
  twitter: Twitter,
  instagram: Instagram,
  youtube: Youtube,
  'message-square': MessageSquare,
  users: UsersIcon,
};

export type IconName = keyof typeof iconComponents;

export const getIconByName = (name?: IconName | null): React.FC<LucideProps> | undefined => {
  if (name && iconComponents[name]) {
    return iconComponents[name];
  }
  return undefined; // Return undefined if not found
};


export const iconPacks: Record<string, IconName[]> = {
  "Genel": ["folder", "list", "file", "favorites", "settings", "personal", "archive", "award", "pin"],
  "Medya": ["music", "image", "video", "game", "tv", "film", "podcast"],
  "İş & Eğitim": ["home", "work", "team", "book", "school", "briefcase"],
  "Geliştirici": ["dev", "cli", "git", "db", "cloud"],
  "Veri & Analitik": ["barChart", "pieChart", "lineChart", "trending"],
  "Ekonomi": ["finance", "ecommerce"],
  "Seyahat & Ulaşım": ["travel", "car", "train", "ship", "anchor", "world", "map"],
};
