/**
 * Sample Data - Örnek Veriler
 * 
 * Task 9: Sosyal, mesaj ve grup örnekleri
 * - Kişisel hesap örnekleri
 * - Organizasyon örnekleri
 * - Sosyal grup örnekleri
 * - Mesaj grubu örnekleri
 */

import { ContentItem } from './initial-content';
import { Conversation, Message } from './store';
import { MessageType } from './messaging-types';

// Örnek Kullanıcılar
export const SAMPLE_USERS = [
  {
    id: 'user-demo-1',
    name: 'Ahmet Yılmaz',
    email: 'ahmet@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ahmet',
    role: 'developer',
    status: 'online' as const,
  },
  {
    id: 'user-demo-2',
    name: 'Elif Kaya',
    email: 'elif@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=elif',
    role: 'designer',
    status: 'online' as const,
  },
  {
    id: 'user-demo-3',
    name: 'Mehmet Demir',
    email: 'mehmet@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mehmet',
    role: 'manager',
    status: 'away' as const,
  },
  {
    id: 'user-demo-4',
    name: 'Zeynep Arslan',
    email: 'zeynep@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=zeynep',
    role: 'content-creator',
    status: 'offline' as const,
  },
  {
    id: 'user-demo-5',
    name: 'Can Öztürk',
    email: 'can@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=can',
    role: 'developer',
    status: 'online' as const,
  },
];

// Örnek Organizasyonlar
export const SAMPLE_ORGANIZATIONS = [
  {
    id: 'org-demo-1',
    name: 'TechFlow Studios',
    description: 'Yazılım geliştirme ve dijital dönüşüm şirketi',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=techflow',
    memberCount: 25,
    isVerified: true,
    category: 'technology',
  },
  {
    id: 'org-demo-2',
    name: 'Creative Labs',
    description: 'Dijital tasarım ve içerik üretim ajansı',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=creative',
    memberCount: 12,
    isVerified: true,
    category: 'design',
  },
  {
    id: 'org-demo-3',
    name: 'Startup Hub',
    description: 'Girişimcilik ve yenilikçilik topluluğu',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=startup',
    memberCount: 150,
    isVerified: false,
    category: 'business',
  },
];

// Örnek Sosyal Gruplar
export const SAMPLE_SOCIAL_GROUPS = [
  {
    id: 'social-group-1',
    name: 'React Türkiye',
    slug: 'react-turkiye',
    description: 'React.js geliştiricileri için Türkçe topluluk',
    coverImage: 'https://images.unsplash.com/photo-1633356122102-3fe601e05bd2?w=800',
    memberCount: 1250,
    postCount: 340,
    category: 'technology',
    isPublic: true,
    isVerified: true,
    tags: ['react', 'javascript', 'frontend', 'web'],
    createdAt: '2023-01-15T10:00:00Z',
  },
  {
    id: 'social-group-2',
    name: 'UI/UX Tasarımcıları',
    slug: 'ui-ux-designers',
    description: 'Tasarım ilkeleri, araçlar ve trendler hakkında paylaşımlar',
    coverImage: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800',
    memberCount: 890,
    postCount: 215,
    category: 'design',
    isPublic: true,
    isVerified: true,
    tags: ['ui', 'ux', 'figma', 'design'],
    createdAt: '2023-03-20T14:30:00Z',
  },
  {
    id: 'social-group-3',
    name: 'Yapay Zeka Meraklıları',
    slug: 'ai-enthusiasts',
    description: 'AI, ML ve deep learning konularında tartışmalar',
    coverImage: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800',
    memberCount: 2100,
    postCount: 520,
    category: 'technology',
    isPublic: true,
    isVerified: false,
    tags: ['ai', 'ml', 'deeplearning', 'gpt'],
    createdAt: '2023-06-10T09:15:00Z',
  },
  {
    id: 'social-group-4',
    name: 'Proje Yönetimi',
    slug: 'project-management',
    description: 'Agile, Scrum ve proje yönetimi metodolojileri',
    coverImage: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800',
    memberCount: 450,
    postCount: 89,
    category: 'business',
    isPublic: false,
    isVerified: false,
    tags: ['agile', 'scrum', 'pm', 'jira'],
    createdAt: '2023-08-05T16:45:00Z',
  },
];

// Örnek Mesaj Grupları
export const SAMPLE_MESSAGE_GROUPS = [
  {
    id: 'msg-group-1',
    name: 'Proje Alpha Ekibi',
    description: 'Alpha projesi için geliştirme ekibi',
    avatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=alpha',
    memberCount: 8,
    isPrivate: true,
    createdAt: '2024-01-10T10:00:00Z',
    lastMessageAt: '2024-01-15T14:30:00Z',
    unreadCount: 3,
  },
  {
    id: 'msg-group-2',
    name: 'Tasarım Revizyonları',
    description: 'UI/UX geri bildirimleri ve revizyonlar',
    avatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=design',
    memberCount: 5,
    isPrivate: true,
    createdAt: '2024-01-08T09:00:00Z',
    lastMessageAt: '2024-01-15T11:20:00Z',
    unreadCount: 0,
  },
  {
    id: 'msg-group-3',
    name: 'Genel Duyurular',
    description: 'Şirket geneli duyurular',
    avatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=announce',
    memberCount: 50,
    isPrivate: false,
    createdAt: '2023-12-01T08:00:00Z',
    lastMessageAt: '2024-01-14T09:00:00Z',
    unreadCount: 1,
  },
];

// Örnek Sohbetler
export const SAMPLE_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv-demo-1',
    userId: 'user-demo-1',
    userName: 'Ahmet Yılmaz',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ahmet',
    lastMessage: 'Toplantı saatini onayladım, yarın görüşürüz!',
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    unreadCount: 0,
    isOnline: true,
    isTyping: false,
    isPinned: false,
    isMuted: false,
    isArchived: false,
    isGroup: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: 'conv-demo-2',
    userId: 'user-demo-2',
    userName: 'Elif Kaya',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=elif',
    lastMessage: 'Tasarım dosyalarını paylaştım, inceleyebilir misin?',
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    unreadCount: 2,
    isOnline: true,
    isTyping: true,
    isPinned: true,
    isMuted: false,
    isArchived: false,
    isGroup: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: 'conv-demo-3',
    userId: 'user-demo-3',
    userName: 'Mehmet Demir',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mehmet',
    lastMessage: 'Haftalık raporu gönderir misin?',
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    unreadCount: 1,
    isOnline: false,
    isTyping: false,
    isPinned: false,
    isMuted: false,
    isArchived: false,
    isGroup: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
];

// Örnek Mesajlar
export const SAMPLE_MESSAGES: Record<string, Message[]> = {
  'conv-demo-1': [
    {
      id: 'msg-1-1',
      conversationId: 'conv-demo-1',
      senderId: 'user-demo-1',
      senderName: 'Ahmet Yılmaz',
      senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ahmet',
      type: MessageType.TEXT,
      content: 'Merhaba! Bugünkü toplantı için hazır mısın?',
      createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
      isRead: true,
      reactions: [],
    },
    {
      id: 'msg-1-2',
      conversationId: 'conv-demo-1',
      senderId: 'current-user',
      senderName: 'Ben',
      type: MessageType.TEXT,
      content: 'Evet, sunumu hazırladım. Saat kaçta başlıyoruz?',
      createdAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
      isRead: true,
      reactions: [],
    },
    {
      id: 'msg-1-3',
      conversationId: 'conv-demo-1',
      senderId: 'user-demo-1',
      senderName: 'Ahmet Yılmaz',
      senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ahmet',
      type: MessageType.TEXT,
      content: 'Toplantı saatini onayladım, yarın görüşürüz!',
      createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
      isRead: true,
      reactions: [{ emoji: '👍', userId: 'current-user', userName: 'Ben' }],
    },
  ],
  'conv-demo-2': [
    {
      id: 'msg-2-1',
      conversationId: 'conv-demo-2',
      senderId: 'user-demo-2',
      senderName: 'Elif Kaya',
      senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=elif',
      type: MessageType.TEXT,
      content: 'Yeni tasarım konseptini tamamladım 🎨',
      createdAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
      isRead: true,
      reactions: [],
    },
    {
      id: 'msg-2-2',
      conversationId: 'conv-demo-2',
      senderId: 'user-demo-2',
      senderName: 'Elif Kaya',
      senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=elif',
      type: MessageType.IMAGE,
      content: 'İşte önizleme:',
      mediaUrl: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400',
      createdAt: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
      isRead: true,
      reactions: [{ emoji: '❤️', userId: 'current-user', userName: 'Ben' }],
    },
    {
      id: 'msg-2-3',
      conversationId: 'conv-demo-2',
      senderId: 'user-demo-2',
      senderName: 'Elif Kaya',
      senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=elif',
      type: MessageType.TEXT,
      content: 'Tasarım dosyalarını paylaştım, inceleyebilir misin?',
      createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
      isRead: false,
      reactions: [],
    },
  ],
};

// Örnek Sosyal Gönderiler (social-post tipi kullanılıyor)
export const SAMPLE_SOCIAL_POSTS: ContentItem[] = [
  {
    id: 'post-demo-1',
    type: 'social-post',
    title: 'Yeni React 19 Özellikleri',
    content: 'React 19 ile gelen yeni özellikler hakkında detaylı bir inceleme hazırladım. Server Components, Actions ve daha fazlası! 🚀',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    parentId: null,
    likeCount: 45,
    commentCount: 12,
    saveCount: 8,
    viewCount: 320,
    tags: ['react', 'javascript', 'frontend'],
    isPublic: true,
  },
  {
    id: 'post-demo-2',
    type: 'social-post',
    title: 'Figma Autolayout İpuçları',
    content: 'Figma\'da autolayout kullanırken işinize yarayacak 10 pratik ipucu. Tasarım sürecinizi hızlandırın! ✨',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    parentId: null,
    likeCount: 78,
    commentCount: 23,
    saveCount: 15,
    viewCount: 560,
    tags: ['figma', 'design', 'ui'],
    isPublic: true,
  },
  {
    id: 'post-demo-3',
    type: 'social-post',
    title: 'AI ile Kod Yazma Deneyimim',
    content: 'Son 1 aydır GitHub Copilot ve Claude ile kod yazıyorum. İşte öğrendiklerim ve önerilerim... 🤖',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    parentId: null,
    likeCount: 156,
    commentCount: 45,
    saveCount: 32,
    viewCount: 1200,
    tags: ['ai', 'coding', 'productivity'],
    isPublic: true,
  },
];

// Örnek Klasör Kapakları için İçerikler
export const SAMPLE_FOLDER_COVERS: ContentItem[] = [
  {
    id: 'folder-cover-demo-1',
    type: 'folder',
    title: 'Eğitim Videoları',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    parentId: null,
    children: [
      {
        id: 'video-1',
        type: 'video',
        title: 'React Temelleri',
        url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        parentId: 'folder-cover-demo-1',
      },
      {
        id: 'video-2',
        type: 'video',
        title: 'TypeScript Başlangıç',
        url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        parentId: 'folder-cover-demo-1',
      },
      {
        id: 'video-3',
        type: 'video',
        title: 'Next.js 14',
        url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        parentId: 'folder-cover-demo-1',
      },
      {
        id: 'video-4',
        type: 'video',
        title: 'Tailwind CSS',
        url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        parentId: 'folder-cover-demo-1',
      },
    ],
  },
  {
    id: 'folder-cover-demo-2',
    type: 'folder',
    title: 'Tasarım Kaynakları',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    parentId: null,
    children: [
      {
        id: 'image-1',
        type: 'image',
        title: 'UI Kit',
        url: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        parentId: 'folder-cover-demo-2',
      },
      {
        id: 'image-2',
        type: 'image',
        title: 'İkon Seti',
        url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        parentId: 'folder-cover-demo-2',
      },
    ],
  },
];

// Tüm örnek verileri dışa aktar
export const SAMPLE_DATA = {
  users: SAMPLE_USERS,
  organizations: SAMPLE_ORGANIZATIONS,
  socialGroups: SAMPLE_SOCIAL_GROUPS,
  messageGroups: SAMPLE_MESSAGE_GROUPS,
  conversations: SAMPLE_CONVERSATIONS,
  messages: SAMPLE_MESSAGES,
  socialPosts: SAMPLE_SOCIAL_POSTS,
  folderCovers: SAMPLE_FOLDER_COVERS,
};

export default SAMPLE_DATA;
